### ISSUE TITLE
How to add options 

### ISSUE THREAD

**Issue by Dipherent** [mohamedshuaau/laravel-sharer#1]
Thank you for this amazing package. I know maybe this is not the right place to post this, but I need help with the following:

My page has a list of job titles that link to external websites. I want to add FB, Twitter, LinkedIn, and Whatsapp share buttons for the links, but when I do, I only see the original link being shared. I want my website name and job title to show, and the url should be the external link..

This is what I have done:

```
<a href="{{ sharer('facebook', $job->source, ['title'=> $job->title]) }}" target="_blank"><i class="px-1 fab fa-facebook-f"></i></a>
```

How can I achieve this using your package?

Thanks

**Comment by mohamedshuaau** [comment]
@Dipherent

Facebook links does not allow you to customize the title, share image etc directly from the url. Instead, Facebook uses Open Graph to configure the shared links further.

You can read more about it [here](https://developers.facebook.com/docs/plugins/share-button/)

The specific code you are looking for are meta tags which looks like these: 

```

<meta property="og:url"           content="https://www.your-domain.com/your-page.html" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="Your Website Title" />
<meta property="og:description"   content="Your description" />
<meta property="og:image"         content="https://www.your-domain.com/path/image.jpg" />

```

You can replace the "content" attribute to your liking and you are good to go 😁
